# NOTE These packages are only used for the inference benchmark,
#      thus they really don't need to be precompiled.
[SnoopPrecompile]
skip_precompile = ["CSV", "DataFrames", "OrdinaryDiffEq", "Plots"]
